# case insensitive
# set to '=1' for enable, all else is disabled
# any non-alpha ('a-z') starting line is a comment

# when loading a new player name, a <player>.arb
# seed file is looked for. this save keeps doors
# for future loads and playthroughs.
# moving or deleting the file will generate a new
# seed on player load.

# if you toggle it while running,
# loading a save should re/un-randomize doors.
enabled=1

# 1<>1 doors, so you can go back the way you came.
# disable if you hate yourself :)
sane_doors=1

# these are each their own 'area' with doors.
# areas with linear 1 time inteded paths are
# disabled by default.
# even then, some doors are excluded to avoid softlocks.
# e.g. three-dog's exit to dupont. popup says 'one-way'.
#      final fight in Anchorage disables controls.
# note: with these off, if the player seed file had
#       an area on, it will still try to load.
#       disabling a DLC that was previously
#       randomized will cancel seed-loads.
#       (you had more doors than now available)
fo3base_enabled=1
vault101child_enabled=0
tranquility_enabled=0
vault87_enabled=0
ravenrock_enabled=0
anchorage_enabled=1
pitt_enabled=1
pointlookout_enabled=1
# zeta is unusable sadly
#zeta_enabled=0
brokensteel_enabled=1
